### ISSUE TITLE
Architecture question regarding repository setup

### ISSUE THREAD

**Issue by jhiemer** [bosh-prometheus/prometheus-boshrelease#154]
Hi,
I have a question regarding the general setup of this repository. With the increasing amount of exporters being added the maintenance and size of the repository is increasing. What I have been asking myself for quite some while now is the following: wouldn't it make sense to split the repository up into to:

* prometheus-boshrelease: as the core unit containing prometheus, alertmanager, nginx, grafana and bosh/cf_exporter, because it represents as single unit, to monitor a bosh/cf environment and add a..
* prometheus-exporter-boshrelease: containing the increasing amount of exporters being added to the project?

Looking for your feedback on this. :-)

**Comment by frodenas** [comment]
Hey @jhiemer. Apologies for not getting back to you earlier.

I've mixed feelings about this. I've been thinking not about splitting the repo in two but having a repo for each exporter.

On one hand, it's true that is a large repository, but we haven't included new exporters in a while, just upgrading the existing versions. I don't have a feeling that using different releases will require more or less maintenance effort, besides the initial split and setup of CI pipelines for each of them. Sprawling exporters might make deploying all the bits more difficult, we will need to maintain a `prometheus-deployment` tracking all exporter release versions. Also, exporters, alerts, and dashboards are quite coupled, I haven't explored yet what will happen if we split the exporters.

On the other hand, having separated releases will mean each exporter having its own lifecycle, which it's good because right now, upgrading an exporter version requires upgrading the whole prometheus bosh release. It will also help deploying exporters as addons (best practice recommends deploying the exporters colocated with the target system, and will help deploying them on OpsManager, where we don't have control over the generated deployment manifest). Also, we can have different owners for each exporter release.

Just out of curiosity, what drove you to start thinking about this? Do you feel that the installation/upgrade process of the release is cumbersome? Did you run into any problems?

I'd also love to hear other opinions /cc @mkuratczyk @jmcarp @aveyrenc @cppforlife

**Comment by mkuratczyk** [comment]
My only opinion is that I don't feel any pain with the current setup to be honest - it works for me as a consumer/deployer of the release. I'd focus on potential release development benefits (independent lifecycle) - I'm perfectly ok with a bit longer deployment manifests if that means that maintenance of the release(s) is simpler.

**Comment by frodenas** [comment]
Closing, please reopen it your concerns were not solved.
