### ISSUE TITLE
No data points for Apps: *

### ISSUE THREAD

**Issue by tomsherrod** [bosh-prometheus/prometheus-boshrelease#175]
Dashboards for all the Apps are returning No data points for majority of the graphs.
The dropdowns contain valid org/space/app. Apps:System doesn't give the cell, along with No data points rest of the graphs.
The prometheus server:9193/metrics and 9186/metrics return values.
How do I find out where things are broken?
Pointers?

**Comment by mylucidreality** [comment]
I am fighting this issue for all my dashboards.  Environment and Deployment drop downs both show None.  It works great for a few days and I always return to this point.  I added the operator to to restart the exporters, but there has been no change.

**Comment by benjaminguttmann-avtq** [comment]
@mylucidreality : Normally, when I see that there is some issue with the bosh exporter; maybe you should check the logs of that exporter because without the bosh exporter almost none of the dashboards will work the right way.

@tomsherrod : Please make sure that your configured the `metrics_environment` with the same name you used in your deployments. A good starting point to find where things are broken is to have a look at the queries used by Grafana.  To check if you are receiving application infos at all you can execute [`cf_application_info`](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/8cba9f89609c1f5d4c39706791a5115613a603c0/jobs/cloudfoundry_dashboards/templates/cf_apps_system.json#L128) in the Prometheus Graph and [ `count(firehose_container_metric_cpu_percentage{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"}) by(instance_index,  bosh_job_ip)` ](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/8cba9f89609c1f5d4c39706791a5115613a603c0/jobs/cloudfoundry_dashboards/templates/cf_apps_system.json#L183) and change the variables with the values form the cf_application_info command.

**Comment by mylucidreality** [comment]
@benjaminguttmann-avtq It looks like the exporters are my issue.  I have logs full of errors around "Invalid refresh token (expired)".  Thanks for responding.

**Comment by lordcf** [comment]
@benjaminguttmann-avtq i am facing the same but only on bosh-jobs and bosh-overview stating as "No data point"
Also i am unable to see environment: deployment: &  Jobs: name visible.
Rest of my dashboard is working perfectly fine.
Any thing wrong went from my end.

**Comment by benjaminguttmann-avtq** [comment]
@lordcf : Did you check the bosh_exporter logs, perhaps there is something mentioned. Sometimes a restart of the exports will help. 

In addition, can you please check if you are able to see values for `bosh_job_healthy` in Prometheus Graph? If you get not data please also try to switch from `console` to `graph` mode and increase the timerange to see if you received some data before.

**Comment by tomsherrod** [comment]
The runtime deployment name defaulted to "cf". I changed the metrics_environment variable from the system_domain to "cf", system_domain was still the deployment in the drop down and no data.
Changed the metron_deployment_name from the system_domain to "cf", metrics came pouring in!

(Closing this issue since the original topic has been resolved.)

**Comment by lordcf** [comment]
@benjaminguttmann-avtq thank you for the reploy.
bosh_exporter dosenot show any other logs apart from invalid login. So we fixed that. 
Apart from that bosh_job_healthy shows logs and and graph is also visible.
Please find the screenshot below:

![prometheus](https://user-images.githubusercontent.com/25821409/38353351-cbc79c8e-38d3-11e8-92eb-fdd4fed81abd.PNG)
![prometheus graph](https://user-images.githubusercontent.com/25821409/38353352-cc02a216-38d3-11e8-94fa-ded044c8cd1e.PNG)

**Comment by frodenas** [comment]
Thanks @benjaminguttmann-avtq for answering those questions!
