### ISSUE TITLE
Data not populated on Bosh_jobs and Bosh_overview after prometheus upgrade to v18.0.0

### ISSUE THREAD

**Issue by lordcf** [bosh-prometheus/prometheus-boshrelease#180]
Bosh_Jobs and Overview dashboard shows no datapoint although other dashboard is working fine.
Added templates and bosh_exporter to the manifest file but still the issue persist.

Can we have other way to get this working.
![bosh](https://user-images.githubusercontent.com/25821409/38353651-b48f74be-38d4-11e8-9b73-e16006a9b75d.PNG)

**Comment by benjaminguttmann-avtq** [comment]
@lordcf : Did you check the bosh_exporter logs, perhaps there is something mentioned. Sometimes a restart of the exports will help.

In addition, can you please check if you are able to see values for bosh_job_healthy in Prometheus Graph? If you get not data please also try to switch from console to graph mode and increase the timerange to see if you received some data before.

**Comment by benjaminguttmann-avtq** [comment]
@lordcf and which version did you use before upgrading to v18.0.0

**Comment by lordcf** [comment]
@benjaminguttmann-avtq thank you for the reploy.
bosh_exporter dosenot show any other logs apart from invalid login. So we fixed that.
Bosh_job_healthy shows logs and and when we change the time range to lets say 1W.
Please find the screenshot below:
![graph](https://user-images.githubusercontent.com/25821409/38354255-8994a9ee-38d6-11e8-9cd3-0f41ad620626.PNG)

I added the template of bosh_exporter and jobs of bosh_exporter, however i also see bosh_dashboard in the jobs. Dose both do the same task or can we remove one.

Before upgrade we were using 13.0.1 and that seems to be pretty old.

**Comment by benjaminguttmann-avtq** [comment]
@lordcf : Thanks for the information. That is strange. Normally, when you are able to see data in the prometheus graph for `bosh_job_healthy` at least the drop downs in the bosh_dashboards in grafana should be populated because it gathers its values from the keys of the `bosh_job_healthy`. 

As you can see [at this point](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/7b7bdccbe295b6b46b14f08501261a4da4c8cbd3/jobs/bosh_dashboards/templates/bosh_overview.json#L1158) the environment dropdown will get its values from the environment key.

**Comment by benjaminguttmann-avtq** [comment]
There is also the way to make the dashboard `editable` to check the templating and queries of the specific panels. Sometimes this also helps to find the problem.

**Comment by lordcf** [comment]
@benjaminguttmann-avtq 
umm...no the problem is not fixed after the suggestion. I am working with few more sceanerios and once it is done ill share you my latest logs for bosh dashboard  which is not working.

**Comment by lordcf** [comment]
@benjaminguttmann-avtq  @frodenas 
Still we are facing the issue with bosh:jobs and overview dashboard. We did added the template for bosh exporter and also the bosh job.

Also we found that /var/vcap/jobs/prometheus/config/prometheus.yml file contains the ip which is not relevant to our bosh so we did the changes to that ip and redeployed. Now is there any other way to get this done
please find the attachment of the prometheus logs file : 
![screen shot 04-17-18 at 05 07 pm](https://user-images.githubusercontent.com/25821409/38867976-3285f02c-4263-11e8-81ce-591550673abc.PNG)
![screen shot 04-17-18 at 05 03 pm](https://user-images.githubusercontent.com/25821409/38867989-3906bd96-4263-11e8-8c3e-0bedde8c3148.PNG)

**Comment by benjaminguttmann-avtq** [comment]
Hi @lordcf, I am a bit confused. What do you mean by 'contains the ip which is not relevant to our bosh' ? Do you mean the bosh exporter with bosh? Because normally the IP of your bosh director should not be in the prometheus config, you should find it in the bosh_exporter ctl script under `/var/vcap/jobs/bosh_exporter/bin/bosh_exporter_ctl`. Perhaps it would be a good idea to validate the data you can see in this file by manually trying to login to the uaa of your bosh director (not the uaa of your CF deployment) .

**Comment by lordcf** [comment]
hi @benjaminguttmann-avtq @frodenas 
i am able to get the value on grafana if i m creating my own dashboard and passing just the value "bosh_job_healthy" as the JSON query 
![custom](https://user-images.githubusercontent.com/25821409/39241083-5da76330-48a3-11e8-83a2-55385f431e70.png)
and the prometheus is working fine as well with all the graphs
but on the actual dashboard of grafana i am not able to see the graph because values are not getting passed from prometheus to grafana i guess .
there might be some stack from where grafana is taking those variables and values..so can can u please tell me wer can i find those variables for bosh

**Comment by lordcf** [comment]
grafana is able to create a graph from query : bosh_job_healthy
but grafana is not able to vreate a graph from query :grinning: 
 "expr": "min(bosh_job_healthy{environment=~\"$environment\",bosh_name=~\"$bosh_director\",bosh_deployment=~\"$bosh_deployment\",bosh_job_name=~\"$bosh_job_name\",bosh_job_index=~\"$bosh_job_index\"})",

**Comment by benjaminguttmann-avtq** [comment]
Do you have problems for your own dashboard or for any specific dashboard that is part of prometheus bosh release?

**Comment by frodenas** [comment]
Closing this issue, please reopen if the problem still persists.
