### ISSUE TITLE
Edit existing dashboards

### ISSUE THREAD

**Issue by manaspatkar21** [bosh-prometheus/prometheus-boshrelease#216]
I want to edit the existing dashboards in Grafana, however I cannot even though I have "Admin" permissions. I changed the "editable" property in the dashboards from "false" to "true" but that did not help.

Any help is appreciated

**Comment by mkuratczyk** [comment]
When you make it editable, Grafana creates a copy of that dashboard. You'll see you have 2 dashboards with the same name - one editable and one not editable. This is because Grafana supports storing dashboards in two formats - as read-only JSON files or stored in its database. This bosh release provides them as JSON files. When you click editable it will import it to the database and make it editable.
