### ISSUE TITLE
Cloud Foundry Org, Space, and Org Quota Dashboards are incorrect

### ISSUE THREAD

**Issue by amhuber** [bosh-prometheus/prometheus-boshrelease#336]
All three dashboards are calculating quota memory usage based on the app's memory limit but not multiplying by the number of instances.  For example, if I push an app with a memory limit of 1G and push 21 instances with a quota of 20GB, then the app will fail to push with an error that I'm exceeding my quota, so the number of instances is clearly a factor in quota usage.  The dashboard on the other hand is only showing 1GB which is the amount of memory set on the app.

The fix is to simply multiple the memory by the number of instances, linking by application_id.  For example, here is the query on the Org Summary dashboard before and after the fix:

Current:

    sum(avg(cf_application_memory_mb{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\"}) by(application_id))

Fixed:

    sum(avg(cf_application_memory_mb{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\"} * on (application_id) cf_application_instances{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\"}) by(application_id))

**Comment by lrstanley** [comment]
We noticed this as well. We don't directly use this release for dashboards, but we have copied them out into our own deployment. We ended up creating a single dashboard for all environments.

I don't quite think using `avg()` is necessary at all. If you group_left by the `instance_id`, you can just sum at that point. The below examples are more complex, but our goal was to get an overall foundation health dashboard, where we didn't have to use dropdowns to change orgs and go through all of them..

Example environment (grafana label being `{{ environment }}/{{ organization_name }}`) with % mem used, where one groups left with the state to get only running apps, then grouping left with the instance_id:

```
(
    sum(
        sum(cf_application_memory_mb) by(environment, organization_name, application_id)
        * on(environment, organization_name, application_id) group_left(state) cf_application_info{state="STARTED", organization_name!~"system|appdynamics.*|p-.*"}
        * on(environment, organization_name, application_id) group_left(instance_id) cf_application_instances_running{state="STARTED", organization_name!~"system|appdynamics.*|p-.*"}
    ) by(environment, organization_name)
    / on(environment, organization_name) cf_organization_total_memory_mb_quota > 0
) * 100 > $quota_limit
```

(we also strip out things like system, appdynamics, p-.*, because they're system based things which our users don't care about).

Similar here, however with spaces (label being `{{ environment }}/{{ organization_nam }}/{{ space_name }}`):

```
sum(
    (
        sum(
            sum(cf_application_memory_mb > 0) by(environment, organization_id, space_id, application_id)
            * on(environment, organization_id, space_id, application_id) group_left(instance_id) cf_application_instances_running{state="STARTED", organization_name!~"system|appdynamics.*|p-.*"}
        ) by (environment, organization_id, space_id)
        / on(environment, organization_id, space_id) sum(cf_space_total_memory_mb_quota > 0) by (environment, organization_id, space_id)
    )
    * on(environment, space_id) group_left(space_name) cf_space_info{organization_name!~"system|appdynamics.*|p-.*"}
    * on(environment, organization_id) group_left(organization_name) cf_organization_info{organization_name!~"system|appdynamics.*|p-.*"}
) by (environment, organization_name, space_name) * 100 > $quota_limit
```

**Comment by amhuber** [comment]
I've submitted https://github.com/bosh-prometheus/prometheus-boshrelease/pull/341 to fix this with the minimal changes required to fix the issues described and get the quotas to align with how CF enforces them only on started apps.

**Comment by frodenas** [comment]
Prometheus BOSH release [26.0.0](https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v26.0.0) contains the fix submitted by @amhuber
