### ISSUE TITLE
plugin grafana-piechart-panel no longer available (should be replaced with piechart plugin?)

### ISSUE THREAD

**Issue by metskem** [bosh-prometheus/prometheus-boshrelease#453]
We are happily running prometheus-boshrelease v27.2.2.
On some dashboards (for example the "CF: Cells Capacity v2") some panels show "Panel plugin not found: grafana-piechart-panel".
When editing the dashboard, you can change it to the "piechart" plugin, and all works again.
So I think this needs to be updated in all the dashboard templates.

If you agree, I'd be happy to file a PR for it.

cheers,
Harry

**Comment by psycofdj** [comment]
Many dashboard are broken because of this, we're on it with @benjaminguttmann-avtq, .

Thanks for the PR offer but we also plan to move forward of grafana 9. Because this bump might/will also break some dashboards, we wanted to fix everything once and for all. We planned to work on this this week but we encountered some problems with the S3 blob repository access.

Until next release, I suggest to revert back to `v27.2.0` or stay like this if you can bare this regression a little longer.

**Comment by psycofdj** [comment]
I added a regression warning on the `v27.2.1` and `v27.2.2` release changelog.

**Comment by metskem** [comment]
Good to hear you are working on Grafana 9. We can wait for it, the currently broken dashboards are no big deal.
Thanks for the quick response, we appreciate.

**Comment by benjaminguttmann-avtq** [comment]
@metskem v28.0.0 which has been released yesterday should fix this issue :)
